### 1. Make a 1D, 2D, 3D array and check shape,size,dimensions and length

In [2]:
import numpy as np

In [ ]:
arr_1D=np.array([1,2,3,4,5,6,7,8,9,10])
print("1D array:",arr_1D)
arr_2D=np.array([[1,2,3],[4,5,6]])
print("2D array:",arr_2D)
arr_3D=np.array([[[10,20], [30,40], [50,60], [70,80]]])
print("3D array:",arr_3D)

1D array: [ 1  2  3  4  5  6  7  8  9 10]
2D array: [[1 2 3]
 [4 5 6]]
3D array: [[[10 20]
  [30 40]
  [50 60]
  [70 80]]]


In [ ]:
#Shape of arrays
arr_1D.shape

(10,)

In [ ]:
arr_2D.shape

(2, 3)

In [ ]:
arr_3D.shape

(1, 4, 2)

In [ ]:
#size of each array
arr_1D.size

10

In [ ]:
arr_2D.size

6

In [ ]:
arr_3D.size

8

In [ ]:
#dimension of each array
arr_1D.ndim

1

In [ ]:
arr_2D.ndim

2

In [ ]:
arr_3D.ndim

3

In [ ]:
#length of each array
len(arr_1D)

10

In [ ]:
len(arr_2D)

2

In [ ]:
len(arr_3D)

1

# 2.Write Example for each of the following

### i.Arange

In [ ]:
arr=np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


### ii.Random.rand and random.randint

In [ ]:
arr1=np.random.rand(10)
print(arr1)
arr2=np.random.randint(3,5)
print(arr2)

[0.56473794 0.88209711 0.64583071 0.37699488 0.25101706 0.57363007
 0.3391078  0.51247104 0.19133349 0.08882085]
4


### iii.Linespace

In [ ]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

### iv.Ones

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

### v.Zeros

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

vi. Diag

In [ ]:
np.diag(arr_2D)

array([1, 5])

### vii.sum

In [ ]:
np.sum([0.5, 1.5])

2.0

### viii.Min

In [ ]:
np.min(arr_3D)

10

### viii.Max

In [ ]:
np.max(arr_1D)

10

### ix.Mean

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.mean(a)

2.5

### 3. Make an array of student marks of a course(generate random marks).Assume fail criteria is less than 30. find number of students passed and filter failed marks

In [3]:
np.random.seed(42)
student_marks = np.random.randint(0, 101, size=50)


passing_marks = student_marks >= 30
num_students_passed = np.sum(passing_marks)
print("Number of students passed:", num_students_passed)

failed_marks = student_marks[student_marks < 30]
print("Failed marks:",failed_marks)

Number of students passed: 36
Failed marks: [14 20 23  2 21  1 29  1 20 21 14  2  6 20]


### 4. Make a 2D array with random numbers between 1 and 50

In [ ]:
new_array = np.random.randint(50, size=(3, 5))
print(new_array)

[[13 27 31 41 31]
 [ 0 30 11 40 37]
 [16  7  9 27 28]]


### 5. Make a numpy array for all odd numbers between -30 and 10

In [4]:
odd_numbers = np.arange(-29, 11, 2)
print("Array of odd numbers between -30 and 10:")
print(odd_numbers)

Array of odd numbers between -30 and 10:
[-29 -27 -25 -23 -21 -19 -17 -15 -13 -11  -9  -7  -5  -3  -1   1   3   5
   7   9]
